remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark"
markdown: kramdown

repository: "fwehn/Traders-Hub"
logo: "/assets/images/Traders-Hub.png"
masthead_title: "Traders-Hub"

plugins:
  - jekyll-include-cache
##theme: jekyll-theme-cayman

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true