remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark"
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


repository: "fwehn/Traders-Hub"
logo: "/assets/images/Traders-Hub.png"
masthead_title: "Traders-Hub"

plugins:
  - jekyll-include-cache
##theme: jekyll-theme-cayman

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true