title: "Traders-Hub"
description: "Eine Website zum Discord-Server Traders-Hub. Bei Traders-Hub handelt es sich um einen vorwiegend gaming-orientierten Kommunikationsserver."

remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark"
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


repository: "https://github.com/fwehn/Traders-Hub"
logo: "/assets/images/Traders-Hub.png"
masthead_title: "Traders-Hub"

plugins:
  - jekyll-include-cache
  - jekyll-feed
##theme: jekyll-theme-cayman

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true



# Site Author
author:
  name             : "Finn Wehn"
  avatar           : "/assets/images/Avatar-Finn.png"
  bio              : "Moin"
  location         : "Hasenweg 12, 51789 Lindlar"
  email            : "finn.wehn@web.de"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "finn.wehn@web.de"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://traders-hub.de/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fwehn"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram-square"
      url: "https://www.instagram.com/finn_wehn/"

# Site Footer
footer:
  links:
    - label: "Impressum"
      icon: "fas fa-address-book"
      url: /impressum/
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/jCYv5puCeY"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fwehn/Traders-Hub"
